# Generated by Django 4.1.4 on 2023-01-04 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=16)),
                ('start_date', models.DateTimeField()),
                ('days', models.IntegerField(default=5)),
                ('sprint_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devtrack.project')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('category_name', models.CharField(max_length=32)),
                ('category_description', models.TextField(default='')),
                ('project_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devtrack.project')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('feature_name', models.CharField(max_length=32)),
                ('feature_description', models.TextField(default='')),
                ('priority', models.IntegerField(choices=[(1, 'HIGH'), (2, 'MODERATE'), (3, 'LOW')], default=1)),
                ('category_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devtrack.featuregroup')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devtrack.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('bug_name', models.CharField(max_length=32)),
                ('severity', models.IntegerField(choices=[(1, 'SEVERE'), (2, 'MODERATE'), (3, 'WARNING')], default=2)),
                ('terminal_feedback', models.TextField(default='')),
                ('feature_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devtrack.feature')),
            ],
        ),
    ]
