# Generated by Django 4.1.4 on 2023-01-05 02:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devtrack', '0002_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feature',
            name='category_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devtrack.featuregroup'),
        ),
    ]
