# Generated by Django 4.1.4 on 2023-01-05 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtrack', '0003_calendar_time_alter_feature_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 2, 34, 2, 140434)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 2, 34, 2, 140434)),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
