# Generated by Django 4.1.4 on 2023-01-05 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtrack', '0004_sprint_end_date_alter_sprint_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateTimeField(default=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 17, 13, 55, 420304))),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 17, 13, 55, 420304)),
        ),
    ]
