# Generated by Django 4.1.4 on 2023-01-05 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtrack', '0006_alter_sprint_end_date_alter_sprint_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 22, 26, 39, 848459, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 22, 26, 39, 848459, tzinfo=datetime.timezone.utc)),
        ),
    ]
