# Generated by Django 4.1.4 on 2023-01-06 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtrack', '0008_alter_sprint_end_date_alter_sprint_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='sprint_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 20, 5, 1, 120742, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 20, 5, 1, 120742, tzinfo=datetime.timezone.utc)),
        ),
    ]
