# Generated by Django 4.1.4 on 2023-01-06 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtrack', '0010_feature_in_progress_alter_sprint_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 21, 9, 2, 117114, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 21, 9, 2, 117114, tzinfo=datetime.timezone.utc)),
        ),
    ]
